services:
  mcp-run-isolated-python:
    build:
      context: .
    environment:
      PYTHON_DEPENDENCIES: "pydantic"
    ports:
      - "6400:6400"
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
      - systempaths=unconfined
