apiVersion: v1
kind: Pod
metadata:
  name: mcp-run-isolated-python
spec:
  hostUsers: false
  containers:
    - name: mcp-run-isolated-python
      image: kigstn/mcp-run-isolated-python:latest
      securityContext:
        procMount: Unmasked
        capabilities:
          add: ["SETFCAP"]